// js/pages/kanban.js

window.KanbanPage = (function() {

  function render() {
    const currentUser = DataStore.getCurrentUser();
    const isAdmin = currentUser && currentUser.role === 'Administrador';

    return `
      <div class="page-container" style="padding-bottom: 0;">
        <div class="page-header" style="margin-bottom: var(--spacing-4);">
          <div class="page-title">
            <h1>Funil de Conversão</h1>
            <p>Arraste os leads entre as fases do funil</p>
          </div>
          <div class="page-actions" style="display: flex; gap: var(--spacing-2); align-items: center;">
            ${isAdmin ? `
            <button class="btn btn-ghost" id="btn-config-stages" style="display: flex; align-items: center; gap: 6px;">
              <i data-lucide="settings"></i> Configurar Fases
            </button>
            ` : ''}
            <select class="form-select" id="kanban-filter-course" style="width: auto;">
              <option value="">Todos os Cursos</option>
              ${Utils.COURSES.map(c => `<option value="${c}">${c}</option>`).join('')}
            </select>
            <select class="form-select" id="kanban-filter-attendant" style="width: auto;">
              <option value="">Todos os Atendentes</option>
              ${DataStore.getUsers().filter(u => u.role !== 'Secretaria').map(u => `<option value="${u.id}">${u.name}</option>`).join('')}
            </select>
          </div>
        </div>

        <div class="kanban-board" id="kanban-board">
          <!-- Columns generated by init() -->
        </div>
      </div>
    `;
  }

  function getStages() {
    return DataStore.getFunnelStages();
  }

  function renderBoard(filters = {}) {
    const leads = DataStore.getLeads(filters);
    const board = document.getElementById('kanban-board');
    if (!board) return;

    const stages = getStages();

    let html = '';
    stages.forEach(stage => {
      const stageLeads = leads.filter(l => l.funnelStage === stage);
      
      html += `
        <div class="kanban-column" data-stage="${stage}">
          <div class="kanban-column-header">
            <div class="kanban-column-title">${stage}</div>
            <div class="kanban-column-count">${stageLeads.length}</div>
          </div>
          <div class="kanban-column-body" id="col-${stage.replace(/\s+/g, '-')}">
            ${stageLeads.map(lead => {
              const attendant = DataStore.getUser(lead.attendantId);
              return `
                <div class="kanban-card" draggable="true" data-id="${lead.id}">
                  <div class="kanban-card-name">${lead.name}</div>
                  <div class="kanban-card-course">
                    <i data-lucide="book-open"></i> ${lead.course}
                  </div>
                  <div class="kanban-card-meta">
                    <div class="kanban-card-date">
                      <i data-lucide="clock"></i>
                      ${Utils.formatRelativeTime(lead.lastUpdate)}
                    </div>
                    ${attendant ? `<div class="avatar kanban-card-avatar" title="${attendant.name}">${attendant.avatar}</div>` : ''}
                  </div>
                </div>
              `;
            }).join('')}
          </div>
        </div>
      `;
    });

    board.innerHTML = html;
    if (window.lucide) window.lucide.createIcons();
    setupDragAndDrop();
  }

  function setupDragAndDrop() {
    const cards = document.querySelectorAll('.kanban-card');
    const columns = document.querySelectorAll('.kanban-column-body');

    cards.forEach(card => {
      card.addEventListener('dragstart', (e) => {
        card.classList.add('dragging');
        e.dataTransfer.setData('text/plain', card.dataset.id);
        e.dataTransfer.effectAllowed = 'move';
      });

      card.addEventListener('dragend', () => {
        card.classList.remove('dragging');
        columns.forEach(col => col.parentElement.classList.remove('drag-over'));
      });

      card.addEventListener('click', () => {
        window.App.navigate(`lead-detail/${card.dataset.id}`);
      });
    });

    columns.forEach(column => {
      column.addEventListener('dragover', (e) => {
        e.preventDefault(); // allow drop
        e.dataTransfer.dropEffect = 'move';
        column.parentElement.classList.add('drag-over');
      });

      column.addEventListener('dragleave', () => {
        column.parentElement.classList.remove('drag-over');
      });

      column.addEventListener('drop', (e) => {
        e.preventDefault();
        column.parentElement.classList.remove('drag-over');
        
        const leadId = e.dataTransfer.getData('text/plain');
        const newStage = column.parentElement.dataset.stage;
        
        if (leadId && newStage) {
          DataStore.updateLeadStage(leadId, newStage);
          Toast.success(`Movido para ${newStage}`);
          // Re-render board with current filters
          applyFilters(); 
        }
      });
    });
  }

  function applyFilters() {
    const course = document.getElementById('kanban-filter-course').value;
    const attendant = document.getElementById('kanban-filter-attendant').value;
    renderBoard({ course, attendantId: attendant });
  }

  // --- Stage Configuration Modal ---

  function openConfigModal() {
    const stages = getStages();

    let listHtml = stages.map((stage, index) => `
      <div class="config-stage-item" data-index="${index}" style="display: flex; align-items: center; gap: 10px; padding: 10px 12px; background: var(--bg-secondary); border-radius: 8px; margin-bottom: 8px;">
        <i data-lucide="grip-vertical" style="color: var(--text-muted); cursor: grab; flex-shrink: 0;"></i>
        <span style="flex: 1; font-weight: 500;">${stage}</span>
        <button class="btn-icon btn-ghost" onclick="window.KanbanPage.renameStage('${stage.replace(/'/g, "\\'")}')" title="Renomear">
          <i data-lucide="edit-3"></i>
        </button>
        <button class="btn-icon btn-ghost text-error" onclick="window.KanbanPage.removeStage('${stage.replace(/'/g, "\\'")}')" title="Excluir">
          <i data-lucide="trash-2"></i>
        </button>
      </div>
    `).join('');

    Modal.show({
      title: 'Configurar Fases do Funil',
      content: `
        <p class="text-muted" style="margin-bottom: 16px; font-size: 0.85rem;">
          Adicione, renomeie ou exclua colunas do Kanban. Colunas com leads não podem ser excluídas.
        </p>
        <div id="stages-list" style="max-height: 350px; overflow-y: auto; margin-bottom: 16px;">
          ${listHtml}
        </div>
        <div style="display: flex; gap: 8px;">
          <input type="text" class="form-input" id="new-stage-name" placeholder="Nome da nova fase..." style="flex: 1;">
          <button class="btn btn-primary" onclick="window.KanbanPage.addNewStage()">
            <i data-lucide="plus"></i> Adicionar
          </button>
        </div>
      `,
      footer: `
        <button class="btn btn-ghost" onclick="Modal.hide()">Fechar</button>
      `
    });

    if (window.lucide) window.lucide.createIcons();

    // Allow Enter key to add
    setTimeout(() => {
      const input = document.getElementById('new-stage-name');
      if (input) {
        input.addEventListener('keydown', (e) => {
          if (e.key === 'Enter') {
            e.preventDefault();
            window.KanbanPage.addNewStage();
          }
        });
      }
    }, 100);
  }

  function addNewStage() {
    const input = document.getElementById('new-stage-name');
    if (!input) return;

    const name = input.value.trim();
    if (!name) {
      Toast.error('Digite um nome para a nova fase.');
      return;
    }

    const result = DataStore.addFunnelStage(name);
    if (result === false) {
      Toast.error('Já existe uma fase com esse nome.');
      return;
    }

    Toast.success(`Fase "${name}" adicionada!`);
    openConfigModal(); // refresh modal
    renderBoard(); // refresh board behind
  }

  function removeStage(name) {
    const result = DataStore.removeFunnelStage(name);

    if (result && result.error === 'HAS_LEADS') {
      Toast.error(`Impossível excluir: existem ${result.count} lead(s) nesta fase. Mova-os primeiro.`);
      return;
    }

    if (result === false) {
      Toast.error('Erro ao excluir fase.');
      return;
    }

    Toast.success(`Fase "${name}" excluída!`);
    openConfigModal(); // refresh modal
    applyFilters(); // refresh board behind
  }

  function renameStage(oldName) {
    // Replace the modal content with a rename prompt
    Modal.show({
      title: 'Renomear Fase',
      content: `
        <div class="form-group">
          <label class="form-label">Nome atual: <strong>${oldName}</strong></label>
          <input type="text" class="form-input" id="rename-stage-input" value="${oldName}" placeholder="Novo nome...">
        </div>
      `,
      footer: `
        <button class="btn btn-ghost" onclick="window.KanbanPage.openConfigModal()">Voltar</button>
        <button class="btn btn-primary" onclick="window.KanbanPage.confirmRename('${oldName.replace(/'/g, "\\'")}')">Salvar</button>
      `
    });

    setTimeout(() => {
      const input = document.getElementById('rename-stage-input');
      if (input) {
        input.select();
        input.addEventListener('keydown', (e) => {
          if (e.key === 'Enter') {
            e.preventDefault();
            window.KanbanPage.confirmRename(oldName);
          }
        });
      }
    }, 100);
  }

  function confirmRename(oldName) {
    const input = document.getElementById('rename-stage-input');
    if (!input) return;

    const newName = input.value.trim();
    if (!newName || newName === oldName) {
      openConfigModal();
      return;
    }

    const result = DataStore.renameFunnelStage(oldName, newName);
    if (result === false) {
      Toast.error('Já existe uma fase com esse nome ou fase não encontrada.');
      return;
    }

    Toast.success(`Fase renomeada para "${newName}"!`);
    openConfigModal(); // refresh modal
    applyFilters(); // refresh board behind
  }

  function init() {
    renderBoard();

    // Setup filter listeners
    const courseFilter = document.getElementById('kanban-filter-course');
    const attendantFilter = document.getElementById('kanban-filter-attendant');
    
    if (courseFilter) courseFilter.addEventListener('change', applyFilters);
    if (attendantFilter) attendantFilter.addEventListener('change', applyFilters);

    // Setup config button
    const configBtn = document.getElementById('btn-config-stages');
    if (configBtn) {
      configBtn.addEventListener('click', openConfigModal);
    }
  }

  return {
    render,
    init,
    openConfigModal,
    addNewStage,
    removeStage,
    renameStage,
    confirmRename
  };
})();
